swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "JWT token, précédé de 'Bearer '"

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: double
        description: Montant de la transaction
      balance:
        type: number
        format: double
        description: Solde après la transaction
      type:
        type: string
        description: Type de transaction
      category:
        type: string
        description: Catégorie de la transaction
      notes:
        type: string
        description: Notes additionnelles sur la transaction
      accountId:
        type: string
        description: Identifiant du compte bancaire

  Account:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique du compte
      type:
        type: string
        description: Type de compte
      balance:
        type: number
        format: double
        description: Solde disponible
      accountNumber:
        type: string
        description: Numéro de compte

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string

paths:
  /accounts/{accountId}/transactions:
    get:
      tags:
        - Transactions
      summary: Récupérer les transactions d'un compte
      description: |
        Cette requête permet de récupérer l'historique des transactions d'un compte bancaire spécifique.
        
        Fonctionnalités :
        - Récupération paginée des transactions
        - Filtrage par période (date de début et de fin)
        - Tri par date (du plus récent au plus ancien)
        
        Paramètres de pagination :
        - Par défaut, 10 transactions par page
        - Possibilité de modifier le nombre d'éléments par page
        - Numérotation des pages à partir de 1
        
        Notes importantes :
        - L'authentification est requise via un token JWT valide
        - Le compte doit exister
        - Les dates de filtrage sont optionnelles
        - Si aucune date n'est spécifiée, toutes les transactions sont retournées
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Attach Bearer JWT token
        - name: accountId
          in: path
          required: true
          type: string
          description: Identifiant du compte
        - name: startDate
          in: query
          required: false
          type: string
          format: date
          description: Date de début pour le filtrage
        - name: endDate
          in: query
          required: false
          type: string
          format: date
          description: Date de fin pour le filtrage
        - name: page
          in: query
          required: false
          type: integer
          default: 1
          description: Numéro de la page
        - name: limit
          in: query
          required: false
          type: integer
          default: 10
          description: Nombre d'éléments par page
      security:
        - Bearer: []
      responses:
        200:
          description: Liste des transactions récupérée avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        401:
          description: Non autorisé
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Compte non trouvé
          schema:
            $ref: '#/definitions/Error'

    post:
      tags:
        - Transactions
      summary: Créer une nouvelle transaction
      description: |
        Cette requête permet de créer une nouvelle transaction pour un compte.
        
        Champs obligatoires :
        - amount (montant de la transaction)
        - type (type de transaction)
        - description
        
        Champs optionnels :
        - category (catégorie de la transaction)
        - notes (notes additionnelles)
        
        Notes importantes :
        - L'authentification est requise via un token JWT valide
        - Le compte doit exister
        - Le montant doit être valide
        - La date sera automatiquement définie à la date actuelle
        
        **Remarque :** Lors de la création, la réponse contient un champ `id` qui correspond à l'identifiant unique de la transaction. Cet identifiant doit être utilisé comme `transactionId` dans les routes permettant de consulter, modifier ou supprimer cette transaction (par exemple : `/accounts/{accountId}/transactions/{transactionId}`).
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Token JWT d'authentification
        - name: accountId
          in: path
          required: true
          type: string
          description: Identifiant du compte
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - amount
              - type
              - description
            properties:
              amount:
                type: number
                format: double
                description: Montant de la transaction
              type:
                type: string
                description: Type de transaction (débit/crédit)
              description:
                type: string
                description: Description de la transaction
              category:
                type: string
                description: Catégorie de la transaction (optionnel)
              notes:
                type: string
                description: Notes additionnelles (optionnel)
      security:
        - Bearer: []
      responses:
        201:
          description: |
            Transaction créée avec succès.
            L'identifiant unique de la transaction (`id`) est retourné dans la réponse.
            Cet identifiant doit être utilisé comme `transactionId` pour accéder, modifier ou supprimer cette transaction via les autres endpoints.
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: |
            Données invalides. Les raisons possibles sont :
            - Format de données incorrect
            - Montant invalide
            - Type de transaction invalide
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Non autorisé
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Compte non trouvé
          schema:
            $ref: '#/definitions/Error'

  /accounts/{accountId}/transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Récupérer les détails d'une transaction
      description: |
        Cette requête permet d'obtenir les informations détaillées d'une transaction spécifique.
        
        Informations retournées :
        - Date et heure de la transaction
        - Montant et type de transaction
        - Description et catégorie
        - Notes additionnelles
        - Solde du compte après la transaction
        
        Notes importantes :
        - L'authentification est requise via un token JWT valide
        - Le compte et la transaction doivent exister
        - La transaction doit appartenir au compte spécifié
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Attach Bearer JWT token
        - name: accountId
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        200:
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/Transaction'
        401:
          description: Non autorisé
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Transaction non trouvée
          schema:
            $ref: '#/definitions/Error'
    
    patch:
      tags:
        - Transactions
      summary: Modifier une transaction
      description: |
        Cette requête permet de modifier les informations d'une transaction existante.
        Seules les propriétés 'category' et 'notes' peuvent être modifiées.
        
        Exemple d'utilisation :
        ```json
        {
          "category": "Nouvelle catégorie",
          "notes": "Notes additionnelles sur la transaction"
        }
        ```
        
        Notes importantes :
        - L'authentification est requise via un token JWT valide
        - Le compte et la transaction doivent exister
        - Les modifications sont partielles (PATCH), seuls les champs fournis seront mis à jour
        - Les champs non fournis resteront inchangés
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Token JWT d'authentification, format "Bearer {token}"
        - name: accountId
          in: path
          required: true
          type: string
          description: Identifiant unique du compte bancaire
        - name: transactionId
          in: path
          required: true
          type: string
          description: Identifiant unique de la transaction à modifier
        - name: body
          in: body
          schema:
            type: object
            properties:
              category:
                type: string
                description: Nouvelle catégorie de la transaction (optionnel)
                example: "Alimentation"
              notes:
                type: string
                description: Notes à ajouter à la transaction (optionnel)
                example: "Achat au supermarché"
      security:
        - Bearer: []
      responses:
        200:
          description: Transaction modifiée avec succès
          schema:
            $ref: '#/definitions/Transaction'
        400:
          description: |
            Données invalides. Les raisons possibles sont :
            - Format de données incorrect
            - Catégorie invalide
            - Notes trop longues
          schema:
            $ref: '#/definitions/Error'
        401:
          description: |
            Non autorisé. Les raisons possibles sont :
            - Token JWT manquant
            - Token JWT invalide
            - Token JWT expiré
          schema:
            $ref: '#/definitions/Error'
        404:
          description: |
            Transaction non trouvée. Les raisons possibles sont :
            - Le compte n'existe pas
            - La transaction n'existe pas
            - La transaction n'appartient pas au compte spécifié
          schema:
            $ref: '#/definitions/Error'
    
    delete:
      tags:
        - Transactions
      summary: Supprimer une transaction
      description: |
        Cette requête permet de supprimer une transaction existante.
        
        Notes importantes :
        - L'authentification est requise via un token JWT valide
        - Le compte et la transaction doivent exister
        - La transaction doit appartenir au compte spécifié
        - Seules les transactions futures peuvent être supprimées
        - La suppression d'une transaction passée n'est pas autorisée
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Token JWT d'authentification
        - name: accountId
          in: path
          required: true
          type: string
          description: Identifiant du compte
        - name: transactionId
          in: path
          required: true
          type: string
          description: Identifiant de la transaction
      security:
        - Bearer: []
      responses:
        204:
          description: Transaction supprimée avec succès
        400:
          description: |
            Suppression impossible. Les raisons possibles sont :
            - Tentative de suppression d'une transaction passée
            - Transaction déjà supprimée
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Non autorisé
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Transaction non trouvée
          schema:
            $ref: '#/definitions/Error'

  /accounts/{accountId}:
    get:
      tags:
        - Comptes
      summary: Récupérer les informations d'un compte
      description: |
        Cette requête permet d'obtenir les informations détaillées d'un compte bancaire.
        
        Informations retournées :
        - Type de compte (courant, épargne, etc.)
        - Solde actuel
        - Numéro de compte
        - Identifiant unique
        
        Notes importantes :
        - L'authentification est requise via un token JWT valide
        - Le compte doit exister
        - L'utilisateur doit être autorisé à accéder à ce compte
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          description: Attach Bearer JWT token
        - name: accountId
          in: path
          required: true
          type: string
      security:
        - Bearer: []
      responses:
        200:
          description: Informations du compte récupérées avec succès
          schema:
            $ref: '#/definitions/Account'
        401:
          description: Non autorisé
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Compte non trouvé
          schema:
            $ref: '#/definitions/Error'